name: productivity_assistant
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  provider: ^6.0.5
  firebase_auth: ^4.15.3
  google_fonts: ^6.1.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  flutter_slidable: ^3.0.1
  calendar_timeline: ^1.1.2

  flutter_lints: ^2.0.0



flutter:
  generate: true

  uses-material-design: true
  assets:
    - assets/images/


